cisplatin = "Abiplatin (IL, NZ, TW); Accocit (CR, DO, GT, HN, NI, PA, SV); Bioplatino (PE); Blastolem (CL, CO, CR, DO, GT, HN, NI, PA, SV); Blastolem RU (MX); Cesalin (BD, LK); Ciscan (ID); Cisly (LU); Cispatin (KR); Cisplan (KR); Cisplat (IN); Cisplatin (AU, ID, IN, NZ); Cisplatin Ebewe (HU); Cisplatin medac (LU); Cisplatin Teva (HU); Cisplatine-Lilly (LU); Cisplatino (CO, EC, PE); Cisplatinum Cytosafe-Delta West (LU); Cisplatyl (FR, SA); Cisteen (PH, ZW); Citoplatino (IT); Citoplax (BR); Cysplack (PH); Cytoplatin (EG, LB); Elvecis (AR); Fangtan (CN); Incel (BR, PY); Kemocarb (VN); Kemoplat (IN, PH, SG, TW, ZW); Lederplatin (DK); Noveldexis (CR, DO, GT, HN, MX, NI, PA, SV); Oncotin (PH); P&U Cisplatin (ZA); Placis (ES, JO, TH, TR); Platamine (AE, BH, CY, HR, IQ, IR, IT, JO, LB, LY, OM, SA, SY, YE); Platiblastin (CH, DE); Platicin (LK); Platidiam (BG, CZ, HN, HU, PL, RU); Platimit (HR); Platin (PH); Platinex (BD, HR, IT); Platinol (AR, AT, BE, CH, EE, FI, GR, LU, SE, UY); Platistil (PT); Platistin (FI, SE); Platistine (LU); Platol (ET, MY, ZW); Platosin (GB, KR, MY, PK, RO, TH); Randa (JP); Sicatem (PY); Sinplatin (BG, RO); Tecnoplatin (MX); Unistin (EG)"

temozolomide = "Accotim (LB); Advecit (TR); Astrodal (SG); Astromide (AU, NZ); Blastomat (HR, LV, NL, RO); Chemtheraz (EG); Dralitem (EC, PY); Emzolam-100 (PH); Niman (CR, DO, GT, HN, NI, PA, SV); Rubrum ASF (CR, DO, GT, HN, NI, PA, SV); Temo (IL); Temobela (VN); Temodal (AE, AR, AT, AU, BE, BG, BH, BO, BR, CH, CL, CN, CO, CR, CY, CZ, DE, DK, DO, EC, EE, EG, ES, FI, FR, GB, GR, GT, HK, HN, HR, HU, ID, IE, IL, IN, IQ, IR, IT, JO, JP, KR, KW, LB, LT, LU, LY, MT, MX, MY, NI, NL, NO, NZ, OM, PA, PE, PH, PL, PR, PT, PY, QA, RO, RU, SA, SE, SG, SI, SK, SV, SY, TH, TR, TW, UA, UY, VE, VN, YE); Temodal IV (SG); Temolde (KR); Temomedac (IE, IS); Temonix (BD); Temoro (ZW); Temotec (LK); Temotero (PH, ZW); Temovex (PH); Temozam (PH); Temozol (LK, PH); Zolomide (BD); Zolotem-250 (TH); Temodar (US); temozolomide (US)"

gemcitabine = "Abine (AR); Abingem (ZW); Bigemax (VN); Celgem (IN); Citabol (ID); Citafine (PH, ZW); Cytogem (ID, IN, UA); DBL (TW); Gemaccord (AU); Gembine (KR); Gembio (PH); Gemcetin (BD); Gemcibine (KR); Gemcikal (ID, PH); Gemcit (BR, KR, LK, PE, PH, TH); Gemedac (ID); Gemezar (JO); Gemflor (TW); Gemhope (PH); Gemita (LK, PH, SG, TH, TW); Gemmis (TW); Gemoxen (BD); Gemplan (AU); Gemresec (SG); Gemtan (KR); Gemtavis (ID); Gemtero (PH, SG, TH, ZW); Gemtin (TH); Gemtra (KR); Gemtro (AR); Gemxit (MX); Gemzar (AE, AT, AU, BB, BF, BG, BJ, BO, BR, CH, CI, CL, CN, CO, CY, CZ, DE, DK, DO, EE, EG, ET, FI, FR, GB, GH, GM, GN, GR, HK, HR, HU, ID, IL, IS, IT, KE, KR, LB, LK, LR, LT, LU, MA, ML, MR, MT, MU, MW, MX, MY, NE, NG, NL, NO, NZ, PA, PE, PH, PK, PL, PR, PT, PY, RO, RU, SA, SC, SD, SE, SG, SI, SK, SL, SN, TH, TN, TR, TW, TZ, UG, UY, VE, VN, ZA, ZM); Getanosan (ID); Gezt (LB, PY); Gitrabin (HK, HR, RO, SG); Oncogem (LB); Oncoril (LK); Pamigen (CR, DO, EC, GT, HN, NI, PA, SV); Zarbin (MX); Zefei (PH); Gemcitabine (); Gemzar (); Infugem ()"

tamoxifen = "Tamoxifen (); Tamoxifen (); APO-Tamox (); DOM-Tamoxifen (); MYLAN-Tamoxifen (); Nolvadex D (); PMS-Tamoxifen (); TEVA-Tamoxifen (); Bilem (TH); Citofen (HR); Crisafeno (PY); Cytotam (LK); Cytotam-10 (ET); Diemon (AR); Fenahex (PH); Genox (AU, NZ); Ginarsan (PE); Ginarsan Forte (PE); Gynatam (PH); Gyraxen (PH); Kessar (CL, FR, GR, IT, ZA); Mamofen (IN, LK); Medtax (PH); Moxafen (AE, BH, CY, IQ, IR, JO, KR, KW, LY, OM, SA, SY, YE); Neophedan (ZA); Neophedan-10 (ZW); Nolvadex (AE, AT, AU, BB, BE, BF, BG, BH, BJ, BM, BR, BS, BZ, CI, CL, CR, CY, DE, DO, EG, ES, ET, FI, FR, GH, GM, GN, GR, GT, GY, HK, HN, HR, IE, IN, IQ, IR, IT, JM, JO, KE, KR, KW, LB, LR, LU, LY, MA, ML, MR, MU, MW, MX, NE, NG, NI, NL, NO, NZ, OM, PA, PK, PL, PR, PT, QA, SA, SC, SD, SE, SG, SL, SN, SR, SV, SY, TN, TR, TT, TW, TZ, UG, VE, VN, YE, ZM, ZW); Nolvadex D (LB, LK, MT); Nolvadex-D (AU, CO, CU, EE, HK, NZ, PH, PY, SG, TH, UY); Novofen (EC, SG, TH, TW); Novofen Forte (BZ, GY, SR); Novofen-D (BB, BM, BS, BZ, GY, JM, NL, PR, SR, TT); Oncotamox (EC); Retaxim (HR); Soltamox (GB, IE); Tadex (FI, TW); Tamec (CH); Tamifen (AE, BH, CY, IQ, IR, JO, KW, LY, OM, SA, SY, YE); Tamifine (VN); Tamizam (BE, LU); Tamodex (EG); Tamofen (CN, DK, FI, HK, TW); Tamofon (AE, JO); Tamona (BD); Tamophar (AE, BH, KW, QA, SA); Tamoplex (BE, KR, PE, PH); Tamorex (KR); Tamosin (AU); Tamox (IE); Tamoxen (BD, HK, PH); Tamoxifen-Eurogenerics (LU); Tamoxifen-Hexal (LU); Tamoxifen-ratioparm (LU); Tamoxifen-Teva (HU); Tamoxifen-Zeneca (LU); Tamoxin (EG); Tamoxis (LK); Tamoxit (LB); Taxus (EC, PE); Tecnofen (MX); Temolex (BD); Xifen (PH); Zitazonium (CZ, HU, PH, RU)"

fluorouracil = "fluorouracil (); Adrucil (); 5-Fluril (BD); 5-FU (DE, JP, KR); Agicil (MT); Fivoflu (IN, JO, PH, VE, ZW); Flonida (IN); Fluonco (PH); Flurablastin (DK, FI, NO, SE); Fluracedyl (BE, MY, NL, PH); Fluroblastin (VE); Fluroblastine (BE); Fluroxan (BD, LK); Fu Ke (CN); La-Fu (CZ); Pharmauracil (PK); Raciwel (LK); Ribofluor (DE); Sinofuan Implant (CN); Triosules (AR); Utoral (PH)"

capecitabine = "capecitabine (); Xeloda (); ACH-Capecitabine (); SANDOZ Capecitabine (); TARO-Capecitabine (); TEVA-Capecitabine (); Xeloda (); Aceda (LB); Ai Bin (CN); Apecitab (AR); Arxeda (RO); Capebina (VN); Capecitabina (PE); Capeda (LB); Capeoda (IT); Capetero (PH, SG); Capibine (IN); Capit (LK); Caponko (PH); Captabine (BD, LK); Capvex (PH); Catacibin (PH); Caxeta (LK, PH); Celabin (PH); Cipatin (TR); Coloxet (CZ, HU, NL); Ecansya (CZ, HU, IE, MT); Intacape (MY, TH); Naprocap (PH); Taceral (ID); Tutabin (RU); Xalvobin (HR, HU); Xelabine (AU); Xelcip (BE, ES, NL); Xelobig (KR); Xelocan (KR); Xelocitabine (AU); Xeloda (AE, AR, AT, BB, BE, BF, BG, BH, BJ, BM, BR, BS, BZ, CH, CI, CL, CN, CO, CR, CU, CY, CZ, DE, DK, DO, EC, EE, EG, ES, ET, FI, FR, GB, GH, GM, GN, GR, GT, GY, HK, HN, HR, HU, IE, IS, IT, JM, JO, JP, KE, KR, KW, LB, LK, LR, LT, LU, MA, ML, MR, MT, MU, MW, MX, MY, NE, NG, NI, NL, NO, NZ, PA, PH, PK, PL, PT, PY, QA, RO, RU, SA, SC, SD, SE, SG, SI, SK, SL, SN, SR, SV, TN, TR, TT, TW, UA, UG, UY, VE, VN, ZA, ZM, ZW); Xeltabine (PH, VN); Xitabin (BD, LK); Zapecine (ES)"

carboplatin = "carboplatin (); Actoplatin (ID); Adcarb (LK); B-Platin (BR); Bagotanilo (MX); Balidon (CO); Biocarb (IN); Biovinate (PH); Biplatinex (VE); Blastocarb (CL, CR, DO, GT, HN, NI, PA, SV); Blastocarb RU (MX); Bobei (CN); Bocartin (VN); Bopacatin (SK); Boplatex (CR, DO, GT, HN, NI, PA, SV); Carbol (ZW); Carbopa (MY); Carboplat (AR, BD, DE, MX); Carboplatin (AE, AU, CY, DK, IL, JO, KW, LB, LT, NO, NZ, PL, SA); Carboplatin a (PT); Carboplatin Abic (TH); Carboplatin DBL (MY); Carboplatin dbl (PT); Carboplatin “Delta West” (HR); Carboplatin-David Bull (LU); Carboplatin-Medac (LU); Carboplatin-Teva (HU); Carboplatino (CU); Carboplatinum Cytosafe-Delta West (LU); Carbosin (BE, GR, ID, KR, LU, PH, ZW); Carbosin Lundbeck (FI); Carbotec (MX); Carbotin (BD); Carbotinol (PH, SA); Carcan (ID); Carplan (KR); Cobalmin (PE); Cycloplatin (CZ, HU); Cytocarb (EG, LB); Delta West Carboplatin (ID, PH); Kemocarb (EG, ID, JO, LK, PH, SG, TH, TW, VN, ZW); Megaplatin (LB); Naprolat (ZW); Naproplat (PH); Neoplatin (KR); Nuvaplast (CR, DO, GT, HN, NI, PA, SV); Omilipis (AR, PY); Oncocarb (PE); Oncocarbin (IN); P&U Carboplatin (ZA); Paraplatin (AT, BG, CH, EC, EE, EG, ES, FI, FR, GB, HK, HN, HR, HU, IE, IT, JO, LU, NL, PH, PT, RU, SE, TR, TW, UY); Pharmaplatin (PK); Unicarb (LK); Vancel (BR, PY); Womaplat (LK); Womastin (LK)"

sorafenib = "sorafenib (); NexAVAR (); Nexavar (AE, AR, AT, AU, BB, BE, BG, BH, BR, CH, CL, CN, CO, CU, CY, CZ, DE, DK, EC, EE, EG, ES, FI, FR, GB, GR, HK, HR, HU, ID, IE, IL, IS, IT, JO, JP, KR, KW, LB, LT, LU, LV, MT, MX, MY, NL, NO, NZ, PE, PH, PL, PT, PY, QA, RO, RU, SA, SE, SG, SI, SK, TH, TR, TW, UY, VN, ZW); Sofenib (BD); Sorafen (BD); Soranib (VN); Soranix (BD)"

measureOfResponse = {
        'clinical progressive disease': 4,
        '[unknown]' : 0,
        'stable disease' : 3,
        'partial response' : 2,
        '[not applicable]' : 0,
        'complete response' : 1,
        '[not available]' : 0, 
        '[discrepancy]' : 0
        }

responses = ["unknown", "complete response", "partial response", "stable disease", "clinical progressive disease"]

nullDrugs = ['[not available]', '[unknown]', 'chemo, nos']

nullDiagnosis = ['not reported']

drugsWithTypeColors = [["darkgreen", "forestgreen"], ["blue", "cornflowerblue"], ["orange", "bisque"], ["red", "lightcoral"]]

